### ISSUE TITLE
NC reports "cannot activate" because it would make server unstable

### ISSUE THREAD

**Issue by JimmyKater** [NastuzziSamy/files_external_gdrive#1]
maybe it would be a good idea to call the app "beta", still?

**Nextcloud version:** 13.0.2 - 13.0.2.1
**Operating system:** Linux 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l
**Webserver:** Apache/2.4.25 (Raspbian) (fpm-fcgi)
**Database:** mysql 10.1.23
**PHP version:** 7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Comment by simonbru** [comment]
I have the same issue when trying to enable it.

**Comment by NastuzziSamy** [comment]
I just released a new verison, it is normally corrected. The app was not compliant that is why

https://github.com/NastuzziSamy/files_external_gdrive/commit/701f9c93ba64b90233ee3e55b2f54ab6d5a961d3

**Comment by JimmyKater** [comment]
ummm... updated to new version - and still can't activate due to same error message

**Comment by NastuzziSamy** [comment]
@JimmyKater do you have more information ? 

I am developping under the same conditions and I dont understand why it tells you that...

**Comment by simonbru** [comment]
@JimmyKater Did you run `composer install` in the application folder ?

**Comment by NastuzziSamy** [comment]
@simonbru did you ? And were you able to enable the app ?

**Comment by simonbru** [comment]
@NastuzziSamy Yes I can enable it without errors.
I couldn't successfully configure an external folder, but I probably misconfigured the app on the Google dev console.

**Comment by JimmyKater** [comment]
@simonbru i downloaded it from the appstore under NC - so no `composer install`
@NastuzziSamy which additional infos do you need? i'll try to provide them

**Comment by JimmyKater** [comment]
are there any dependencies on other apps i need to install? (and that aren't installed, yet)?

**Comment by JimmyKater** [comment]
0.2.2 didn't solve the problem for me. so it was no sideeffect of fixed up/downloads

@NastuzziSamy which question do you have? again: if you need more infos, pls let me know as precisely as possible what you would need... ;)

**Comment by NastuzziSamy** [comment]
@JimmyKater how did you install it ?
Can you let me know if files_external is enabled ?
Can you try to manually install https://github.com/icewind1991/files_external_dropbox/ and tell me if there are any differences ?

Tell me whatever you think relevant

**Comment by NastuzziSamy** [comment]
And @JimmyKater, I am trying to resolve all issues but some of them are easily resolvable, so yeah, 0.2.2 did not have any impact on your issue ;)

**Comment by Amusable-design** [comment]
I tried this with no success.  

But I did see these two PHP errors appear in the log after trying to enable via the web interface:

`require_once(/var/snap/nextcloud/6916/nextcloud/extra-apps/files_external_gdrive/vendor/autoload.php): failed to open stream: No such file or directory at /var/snap/nextcloud/6916/nextcloud/extra-apps/files_external_gdrive/appinfo/app.php#22`

`require_once(): Failed opening required '/var/snap/nextcloud/6916/nextcloud/extra-apps/files_external_gdrive/vendor/autoload.php' (include_path='/snap/nextcloud/6916/htdocs/3rdparty/pear/console_getopt:/snap/nextcloud/6916/htdocs/3rdparty/pear/pear_exception:/snap/nextcloud/6916/htdocs/3rdparty/pear/pear-core-minimal/src:/snap/nextcloud/6916/htdocs/3rdparty/pear/archive_tar:/snap/nextcloud/current/htdocs/apps:/var/snap/nextcloud/current/nextcloud/extra-apps') at /var/snap/nextcloud/6916/nextcloud/extra-apps/files_external_gdrive/appinfo/app.php#22`

FYI, running 13.0.2 from the snap.  Not sure if that makes a difference to the app.

**Comment by JimmyKater** [comment]
@NastuzziSamy 
- how did you install it ? the easiest way - directly from appstore
- Can you let me know if files_external is enabled ? no. it wasn't enabled. and when i enabled it by `ooc: app:enable files_external` it threw 2 errors to nextcloud.log
`require_once(/var/www/nextcloud/apps/files_external_gdrive/vendor/autoload.php): failed to open stream: No such file or directory at /var/www/nextcloud/apps/files_external_gdrive/appinfo/app.php#22`
and
`require_once(): Failed opening required '/var/www/nextcloud/apps/files_external_gdrive/vendor/autoload.php' (include_path='/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/apps') at /var/www/nextcloud/apps/files_external_gdrive/appinfo/app.php#22`

i think i would need to install/enable` files_external_gdrive` as well?

**Comment by NastuzziSamy** [comment]
Ok thanks for the log @PnjDbq and @JimmyKater , it helps me

https://github.com/NastuzziSamy/files_external_gdrive/commit/34d53dc74999548bc1ccf805e98c2bf0370d355d

**Comment by JimmyKater** [comment]
```
0.2.3. didn't really help... 
again 2 errors in NC.log

`Error | PHP | Array to string conversion at /var/www/nextcloud/apps/issuetemplate/lib/DetailManager.php#104`
 and```


Error | index | Exception: Cannot include autoload. Did you run install dependencies using composer?/var/www/nextcloud/lib/private/legacy/app.php - line 245:  require_once()/var/www/nextcloud/lib/private/legacy/app.php - line 154:  OC_App  requireAppFile('files_external_...')/var/www/nextcloud/lib/private/legacy/app.php - line 127:  OC_App  loadApp('files_external_...')/var/www/nextcloud/lib/base.php - line 984:  OC_App  loadApps()/var/www/nextcloud/index.php - line 37:  OC  handleRequest(){main}
-- | -- | --
```


but hey... i like very much your effort you're putting into this! <3

**Comment by Sven-M-2018** [comment]
Same problem here. Here's my log:
`Exception: Cannot include autoload. Did you run install dependencies using composer?

    /www/htdocs/*****/lib/private/legacy/app.php - line 245: require_once()
    /www/htdocs/*****/lib/private/legacy/app.php - line 154: OC_App requireAppFile('files_external_...')
    /www/htdocs/*****/lib/private/legacy/app.php - line 127: OC_App loadApp('files_external_...')
    /www/htdocs/*****/lib/private/legacy/util.php - line 193: OC_App loadApps(Array)
    /www/htdocs/*****/lib/private/Files/Filesystem.php - line 264: OC_Util setupFS('')
    /www/htdocs/*****/lib/private/Server.php - line 261: OC\Files\Filesystem getMountManager(NULL)
    /www/htdocs/*****/3rdparty/pimple/pimple/src/Pimple/Container.php - line 113: OC\Server->OC\{closure}(*** sensitive parameters replaced ***)
    /www/htdocs/*****/lib/private/AppFramework/Utility/SimpleContainer.php - line 116: Pimple\Container->offsetGet('RootFolder')
    /www/htdocs/*****/lib/private/ServerContainer.php - line 132: OC\AppFramework\Utility\SimpleContainer->query('RootFolder')
    /www/htdocs/*****/lib/private/Server.php - line 283: OC\ServerContainer->query('RootFolder')
    [internal function] OC\Server->OC\{closure}(*** sensitive parameters replaced ***)
    /www/htdocs/*****/lib/private/Files/Node/LazyRoot.php - line 61: call_user_func(Object(Closure))
    /www/htdocs/*****/lib/private/Files/Node/LazyRoot.php - line 141: OC\Files\Node\LazyRoot->__call('get', Array)
    /www/htdocs/*****/lib/private/Files/AppData/AppData.php - line 79: OC\Files\Node\LazyRoot->get('appdata_oc9w8y1...')
    /www/htdocs/*****/lib/private/Files/AppData/AppData.php - line 105: OC\Files\AppData\AppData->getAppDataFolder()
    /www/htdocs/*****/apps/end_to_end_encryption/lib/KeyStorage.php - line 99: OC\Files\AppData\AppData->getFolder('/')
    /www/htdocs/*****/apps/end_to_end_encryption/lib/KeyStorage.php - line 95: OCA\EndToEndEncryption\KeyStorage->checkFolderStructure()
    /www/htdocs/*****/apps/end_to_end_encryption/lib/AppInfo/Application.php - line 88: OCA\EndToEndEncryption\KeyStorage->__construct(Object(OC\Files\AppData\AppData), Object(OC\User\Session), Object(OC\Log), Object(OC\Files\Node\LazyRoot), Object(OC\User\Manager))
    /www/htdocs/*****/apps/end_to_end_encryption/appinfo/app.php - line 23: OCA\EndToEndEncryption\AppInfo\Application->registerEvents()
    /www/htdocs/*****/lib/private/legacy/app.php - line 245: require_once('/www/htdocs/w01...')
    /www/htdocs/*****/lib/private/legacy/app.php - line 154: OC_App requireAppFile(Object(OCA\EndToEndEncryption\AppInfo\Application))
    /www/htdocs/*****/lib/private/legacy/app.php - line 127: OC_App loadApp('end_to_end_encr...')
    /www/htdocs/*****/lib/base.php - line 984: OC_App loadApps()
    /www/htdocs/*****/index.php - line 37: OC handleRequest()
    {main}`

**Comment by NastuzziSamy** [comment]
Thanks guys ^^ 

Did you both tried to remove and reinstall it from the appstore ? 

If you really want to use it, you can just run `make` in the app directory

**Comment by Kyrluckechuck** [comment]
@NastuzziSamy that resolved it for me (running make with 0.2.3), however, I'm not 100% sure all is installed inside the snap environment I've got my nextcloud-snap setup with -- it will do though! (and points to dependency issues)

**Comment by JimmyKater** [comment]
@NastuzziSamy 
removed it and re-installed it from the appstore. no changes.


`Error | index | Exception: Cannot include autoload. Did you run install dependencies using composer?/var/www/nextcloud/lib/private/legacy/app.php - line 245:  require_once()/var/www/nextcloud/lib/private/legacy/app.php - line 154:  OC_App  requireAppFile('files_external_...')/var/www/nextcloud/lib/private/legacy/app.php - line 127:  OC_App  loadApp('files_external_...')/var/www/nextcloud/lib/base.php - line 984:  OC_App  loadApps()/var/www/nextcloud/index.php - line 37:  OC  handleRequest(){main}`

and i'd maybe wanna use it productivly after it'll be possbile to read and write from/to g-drive... so no need to ` make` for me now :-/

**Comment by NastuzziSamy** [comment]
@JimmyKater @simonbru @Kyrluckechuck 

I just found the problem. I misunderstood how Nextcloud works and thought when you enable an app, it launches a composer install or at least a make

I will correct that in less an hour

**Comment by NastuzziSamy** [comment]
Fixed and tested https://github.com/NastuzziSamy/files_external_gdrive/commit/4a5bbdd1eb63add566538bdf90c6bfd84979687a

**Comment by JimmyKater** [comment]
0.2.5. took a while to get installed but it worked... and it's activated now. perfect.
thanks man!
